include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    lines_longer_than_80_chars: ignore # modern monitors handle >80 fine

linter:
  rules:
    # --- SAFETY / CORRECTNESS ---
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_null_checks_in_equality_operators
    - use_build_context_synchronously
    - unawaited_futures
    - await_only_futures
    - cast_nullable_to_non_nullable
    - only_throw_errors

    # --- MAINTAINABILITY ---
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - directives_ordering
    - depend_on_referenced_packages
    - unnecessary_lambdas

    # --- READABILITY / STYLE ---
    - camel_case_types
    - file_names
    - prefer_single_quotes
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - use_key_in_widget_constructors

    # --- CLEAN CODE ---
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
